name = "cloud-r2pan"
main = "src/index.ts"
compatibility_date = "2025-01-01"

[vars]
admin = "test123"

[[d1_databases]]
binding = "db"
database_name = "d1"
database_id = "51d2d9b6-48af-4be8-89bc-ee755905dfee"

[[r2_buckets]]
binding = "r2"
bucket_name = "cf-r2"

[[analytics_engine_datasets]]
binding = "analytics"
dataset = "r2pan_downloads"